/** Dashboard home overview — shared client/server types. */

import type { SocialPlatform } from "@/lib/profile/profile-types";
import type { SocialAuthMethod, SocialConnectionStatus } from "@/lib/social-sync/social-sync.types";

export type MetricTrend = "up" | "down" | "flat" | null;

export type DashboardSocialSummary = {
  platform: SocialPlatform;
  connected: boolean;
  username: string;
  avatarUrl: string;
  followers: number | null;
  followersTrend: MetricTrend;
  monthlyViews: number | null;
  monthlyViewsTrend: MetricTrend;
  connection: {
    method: SocialAuthMethod | null;
    status: SocialConnectionStatus;
    oauthAvailable: boolean;
    connectPath: string;
  };
};

export type ActivityRingId = "videos" | "views" | "growth";

export type DashboardActivityRing = {
  id: ActivityRingId;
  label: string;
  current: number;
  goal: number;
  color: string;
};

export type DashboardAiMonthlyTask = {
  id: string;
  label: string;
  completed: boolean;
  /** `ai` when generated by monthly task pipeline; `template` until then. */
  source: "ai" | "template";
};

export type DashboardHomePayload = {
  socialAccounts: DashboardSocialSummary[];
  totals: {
    followers: number;
    monthlyViews: number;
  };
  activityRings: DashboardActivityRing[];
  monthlyTasks: DashboardAiMonthlyTask[];
};

export const DEFAULT_ACTIVITY_RING_GOALS: Record<ActivityRingId, number> = {
  videos: 12,
  views: 100_000,
  growth: 500,
};
